# Generated by Django 4.2.7 on 2024-09-25 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('image', models.ImageField(default=' ', upload_to='media/userimage')),
                ('name', models.CharField(max_length=255)),
                ('phone_Number', models.CharField(default='', max_length=11)),
                ('address', models.CharField(default='', max_length=300)),
                ('Farm_Name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('Farm_Size', models.CharField(blank=True, max_length=1230, null=True)),
                ('Farm_Location', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_expert', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment_time_slot',
            fields=[
                ('time', models.TimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='media/Event/images')),
                ('Blog_title', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Type',
            fields=[
                ('Farm_Type', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video_conference_appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('Description', models.TextField()),
                ('Time', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.appointment_time_slot')),
                ('UserId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=500)),
                ('Phone_Number', models.CharField(max_length=11)),
                ('Message', models.TextField()),
                ('Farm_Type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.farm_type')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Farm_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.farm_type'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
