# Generated by Django 4.2.7 on 2024-09-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_time_slot',
            name='time',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
