# Generated by Django 4.2.7 on 2024-09-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government_Support',
            fields=[
                ('SupportId', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='media/Government_Support')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
