# Generated by Django 4.2.7 on 2024-09-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_government_support_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_conference_appointment',
            name='Topic',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
