# Generated by Django 4.2.7 on 2024-09-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_video_conference_appointment_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_conference_appointment',
            old_name='Data',
            new_name='Date',
        ),
    ]
